const MAIN_SCREEN_APP_BAR_TITLE = 'Discover';
const BEST_SCREEN_BEST_POPULAR_MOVIES_AND_SERIALS = 'BEST POPULAR MOVIE AND SERIALS';
const SHOW_CASES_TITLE = 'SHOWCASES';
const SHOW_CASES_SEE_MORE = 'MORE SHOWCASES';
const BEST_ACTORS_TITLE = 'BEST ACTOR';
const BEST_ACTORS_SEE_MORE = 'MORE ACTOR';